name: Laravel Testing

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  laravel-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Version
        run: docker version

      - name: Create & Start Docker Containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build

      - name: OS Version
        run: |
          docker-compose exec -T app cat /etc/os-release
          docker-compose exec -T app cat /etc/debian_version

      - name: PHP Version
        run: docker-compose exec -T app php --version

      - name: Composer Version
        run: docker-compose exec -T app composer --version

      - name: Install Dependencies
        run: docker-compose exec -T app composer install

      - name: Laravel Version
        run: docker-compose exec -T app php artisan --version

      - name: Laravel Setting
        run: |
          docker-compose exec -T app cp .env.example .env
          docker-compose exec -T app php artisan key:generate
          docker-compose exec -T app cp .env.example .env.testing
          docker-compose exec -T app php artisan key:generate --env=testing
          docker-compose exec -T app sed -i -e 's/AUTH0_DOMAIN=/AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}/' .env.testing
          docker-compose exec -T app sed -i -e 's/AUTH0_CLIENT_ID=/AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}/' .env.testing
          docker-compose exec -T app sed -i -e 's/AUTH0_CLIENT_SECRET=/AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}/' .env.testing
          docker-compose exec -T app sed -i -e 's/AUTH0_TEST_USERNAME=/AUTH0_TEST_USERNAME=${{ secrets.AUTH0_TEST_USERNAME }}/' .env.testing
          docker-compose exec -T app sed -i -e 's/AUTH0_TEST_USER_PASS=/AUTH0_TEST_USER_PASS=${{ secrets.AUTH0_TEST_USER_PASS }}/' .env.testing

      - name: Laravel Migrate Testing
        run: docker-compose exec -T app php artisan migrate --force

      - name: Laravel Rollback Testing
        run: docker-compose exec -T app php artisan migrate:refresh --force

      - name: Laravel Seeding Testing
        run: docker-compose exec -T app php artisan db:seed --force

      - name: Laravel PHPUnit Testing
        run: composer dump-autoload
        run: docker-compose exec -T app php artisan test --env=testing
